### ISSUE TITLE
Black and white media assets aren't showing in the WP > Media section

### ISSUE THREAD

**Issue by andygirvan** [thirtydigital/performancecomms#3]

**Comment by andygirvan** [comment]
Ah ok, so it looks like the media did copy over in the FOLDER but not as a record in the database. 

If you want, I can save and reupload all the assets so they all appear in the wp > media section?

**Comment by andyjmurphy** [comment]
Hmm, does that mean it replaces all the images currently in there? Im trying to cull the media library at the moment by getting rid of duplicates and replacing the big files with smaller versions. Am also trying to categorise them so i can sort them out!

**Comment by andygirvan** [comment]
If you're trying to cull the media library, what I can do is just reduce the size of those assets on the server (so the ones that exist in the wp > uploads folders. 

This does mean that you wouldn't see them as thumbnails in Media at this point.

Let me know which you want:
1 - Asset crunch of the existing black and white thumbnails but wont show in Media 
OR 
2 - Re-upload and reassign of the images so they're smaller but show in Media. This would take a few hours to complete, so i'll let you know when done if you went with this! :)

**Comment by andyjmurphy** [comment]
Well i have been systematically trying to delete duplicates which seem to have crept in there. Once I have the images down to only the ones that should be in there I was going to go through and upload smaller versions of them.

Might be easier just to upload the Black and white ones separately?
On 13 Mar 2017, at 11:56, Andy <notifications@github.com<mailto:notifications@github.com>> wrote:


If you're trying to cull the media library, what I can do is just reduce the size of those assets on the server (so the ones that exist in the wp > uploads folders.

This does mean that you wouldn't see them as thumbnails in Media at this point.

Let me know which you want:
1 - Asset crunch of the existing black and white thumbnails but wont show in Media
OR
2 - Re-upload and reassign of the images so they're smaller but show in Media. This would take a few hours to complete, so i'll let you know when done if you went with this! :)

**Comment by andygirvan** [comment]
Sure, i can sort that out for you! will give you a shout when done :)

**Comment by andygirvan** [comment]
All B+W photos have been uploaded and replaced on the homepage, so they're the latest from WP Admin > Media. I also ran them through a compressor so managed to make the images in total 54% lighter :+1: 
http://performancecomms.com/wp-admin/upload.php
