### ISSUE TITLE
Webmaster Tools Verification

### ISSUE THREAD

**Issue by andyjmurphy** [thirtydigital/performancecomms#5]
Im having problems verifying the websites with Google. I need to place the Google analytics code in the head tag rather than where it currently is. Is there a way around this?

**Comment by andygirvan** [comment]
This should be absolutely fine, I can move the GA code up to the <head>. Is this the only piece of Google-provided code you want moving, or have you been given any webmaster specific code? Like <meta> codes etc...

**Comment by andyjmurphy** [comment]
According to them:

• You must be using the asynchronous tracking code .
• Your tracking code should be in the <head> section of your page.
• You must have the "edit" permission for the Analytics web property.

I think the code they want is just the google analytics recommended code...
On 13 Mar 2017, at 11:51, Andy <notifications@github.com<mailto:notifications@github.com>> wrote:


This should be absolutely fine, I can move the GA code up to the . Is this the only piece of Google-provided code you want moving, or have you been given any webmaster specific code? Like codes etc...

**Comment by andygirvan** [comment]
Ok cool, i'll move that this afternoon and close this ticket when done
